# Generated by Django 5.1.2 on 2025-12-28 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disputes", "0002_alter_dispute_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisputeMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="نص الرسالة")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="disputes/attachments/%Y/%m/",
                        verbose_name="مرفق",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت الإرسال"),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, verbose_name="ملاحظة داخلية (للإدارة فقط)"
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="disputes.dispute",
                        verbose_name="النزاع",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المرسل",
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة نزاع",
                "verbose_name_plural": "رسائل النزاع",
                "ordering": ["created_at"],
            },
        ),
    ]
