# Generated by Django 5.1.2 on 2025-12-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_title",
                    models.CharField(
                        default="تواصل مع فريق سامي لينك",
                        max_length=200,
                        verbose_name="عنوان قسم التواصل",
                    ),
                ),
                (
                    "contact_description",
                    models.TextField(
                        default="للاستفسارات، الشراكات، أو التجربة الأولى للمنصة: يسعدنا تواصلك معنا عبر البريد الإلكتروني أو الواتساب.",
                        verbose_name="وصف قسم التواصل",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="support@samilink.sa",
                        max_length=254,
                        verbose_name="البريد الإلكتروني الرسمي",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        default="0000 000 50 966+",
                        max_length=50,
                        verbose_name="واتساب خدمة العملاء",
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        default="الأحد - الخميس: 8 ص - 5 م",
                        max_length=200,
                        verbose_name="أوقات العمل",
                    ),
                ),
                (
                    "partnership_card_badge",
                    models.CharField(
                        default="جاهزون لمرافقتك 🚀",
                        max_length=100,
                        verbose_name="شارة البطاقة",
                    ),
                ),
                (
                    "partnership_card_title",
                    models.CharField(
                        default="من أول طلب حتى التسليم",
                        max_length=200,
                        verbose_name="عنوان البطاقة",
                    ),
                ),
                (
                    "partnership_card_description",
                    models.TextField(
                        default="يمكن تهيئة المنصة للاستخدام الداخلي في شركتك أو فريقك، مع صلاحيات مالية وإدارية متقدمة وتقارير متابعة مخصصة بحسب احتياج الإدارة.",
                        verbose_name="وصف البطاقة",
                    ),
                ),
                (
                    "partnership_button_text",
                    models.CharField(
                        default="طلب شراكة 👋", max_length=100, verbose_name="نص الزر"
                    ),
                ),
                (
                    "partnership_button_url",
                    models.CharField(
                        default="#", max_length=200, verbose_name="رابط الزر"
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات الموقع والصفحة الرئيسية",
                "verbose_name_plural": "إعدادات الموقع والصفحة الرئيسية",
            },
        ),
    ]
