# Generated by Django 5.1.2 on 2025-12-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="رقم الجوال"
            ),
        ),
    ]
