# Generated by Django 5.2.7 on 2025-11-24 16:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_ledgerentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ledgerentry",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "قيد خزنة",
                "verbose_name_plural": "قيود الخزنة",
            },
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "غير مدفوعة"),
                    ("paid", "مدفوعة"),
                    ("cancelled", "ملغاة"),
                ],
                db_index=True,
                default="unpaid",
                max_length=16,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="المبلغ",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="التاريخ"
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="direction",
            field=models.CharField(
                choices=[("in", "دخول"), ("out", "خروج")],
                max_length=8,
                verbose_name="الاتجاه",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("client_payment", "تحصيل عميل"),
                    ("employee_payout", "صرف موظف"),
                    ("client_refund", "إرجاع عميل"),
                    ("vat_remittance", "توريد ضريبة"),
                ],
                max_length=32,
                verbose_name="نوع القيد",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="finance.invoice",
                verbose_name="فاتورة",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="note",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="ملاحظة"
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="payout",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="finance.payout",
                verbose_name="صرف",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="refund",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="finance.refund",
                verbose_name="مرتجع",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="tax_remittance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="finance.taxremittance",
                verbose_name="توريد ضريبة",
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="صافي المبلغ بعد خصم عمولة المنصّة",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="المبلغ المصروف للموظف",
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد المراجعة"),
                    ("paid", "مدفوع"),
                    ("cancelled", "ملغي"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
        ),
        migrations.AlterField(
            model_name="taxremittance",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد الانتظار"),
                    ("sent", "تم التوريد"),
                    ("cancelled", "ملغي"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
    ]
