# Generated by Django 5.1.2 on 2025-11-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_delete_servicerequest_note_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="client_total_amount_cache",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=12, null=True
            ),
        ),
    ]
