# Generated by Django 5.2.7 on 2025-11-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0009_offer_client_total_amount_cache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "طلب جديد"),
                    ("offer_selected", "تم اختيار عرض"),
                    ("agreement_pending", "اتفاقية بانتظار الموافقة"),
                    (
                        "awaiting_payment_confirmation",
                        "تم قبول الاتفاقية وبانتظار تأكيد الدفع",
                    ),
                    ("in_progress", "قيد التنفيذ"),
                    ("completed", "مكتمل"),
                    ("disputed", "نزاع"),
                    ("cancelled", "ملغى"),
                ],
                db_index=True,
                default="new",
                max_length=32,
            ),
        ),
    ]
