# Generated by Django 5.2.7 on 2025-11-24 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0010_alter_request_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "عرض",
                "verbose_name_plural": "عروض",
            },
        ),
        migrations.AlterField(
            model_name="note",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="الكاتب",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="marketplace.request",
                verbose_name="الطلب",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="client_total_amount_cache",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=12,
                null=True,
                verbose_name="إجمالي العميل (مخزن)",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الموظف",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="note",
            field=models.TextField(blank=True, verbose_name="ملاحظة"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="proposed_duration_days",
            field=models.PositiveIntegerField(verbose_name="المدة المقترحة (أيام)"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="proposed_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="السعر المقترح P"
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="marketplace.request",
                verbose_name="الطلب",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد المراجعة"),
                    ("selected", "العرض المختار"),
                    ("rejected", "مرفوض"),
                    ("withdrawn", "مسحوب"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="assigned_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests_as_employee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الموظف المُسنّد",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests_as_client",
                to=settings.AUTH_USER_MODEL,
                verbose_name="العميل",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="has_dispute",
            field=models.BooleanField(default=False, verbose_name="به نزاع؟"),
        ),
        migrations.AlterField(
            model_name="request",
            name="has_milestones",
            field=models.BooleanField(default=False, verbose_name="يحتوي مراحل؟"),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "طلب جديد"),
                    ("offer_selected", "تم اختيار عرض"),
                    ("agreement_pending", "اتفاقية بانتظار الموافقة"),
                    (
                        "awaiting_payment_confirmation",
                        "تم قبول الاتفاقية وبانتظار تأكيد الدفع",
                    ),
                    ("in_progress", "قيد التنفيذ"),
                    ("completed", "مكتمل"),
                    ("disputed", "نزاع"),
                    ("cancelled", "ملغى"),
                ],
                db_index=True,
                default="new",
                max_length=32,
                verbose_name="الحالة",
            ),
        ),
    ]
