# Generated by Django 5.2.8 on 2025-12-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0011_alter_offer_options_alter_note_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="extension_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="سبب طلب التمديد"
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="extension_requested_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="أيام التمديد المطلوبة"
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="modification_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="سبب التعديل أو الإلغاء"
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="modified_duration_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="المدة بعد التعديل (أيام)"
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="modified_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="السعر بعد التعديل",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد المراجعة"),
                    ("selected", "العرض المختار"),
                    ("rejected", "مرفوض"),
                    ("withdrawn", "مسحوب"),
                    ("modified", "معدل من الموظف"),
                    ("waiting_client_approval", "بانتظار موافقة العميل على التعديل"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
                verbose_name="الحالة",
            ),
        ),
    ]
