# Generated by Django 5.2.8 on 2025-12-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0012_offer_extension_reason_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="offer",
            name="uq_request_single_selected_offer",
        ),
        migrations.RemoveConstraint(
            model_name="offer",
            name="uq_active_offer_per_employee_per_request",
        ),
        migrations.RemoveConstraint(
            model_name="offer",
            name="offer_duration_days_gt_0",
        ),
        migrations.RemoveConstraint(
            model_name="offer",
            name="offer_price_gte_0",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="client_total_amount_cache",
        ),
        migrations.AlterField(
            model_name="offer",
            name="extension_requested_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="عدد أيام التمديد المطلوبة"
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="modification_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="سبب التعديل/الإلغاء"
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="modified_duration_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="المدة بعد التعديل بالأيام"
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="note",
            field=models.TextField(
                blank=True, null=True, verbose_name="ملاحظات إضافية (اختياري)"
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="proposed_duration_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="المدة المقترحة (أيام)"
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="proposed_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="السعر المقترح",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="الحالة"
            ),
        ),
    ]
