# Generated by Django 5.1.2 on 2025-12-03 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0013_alter_offer_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="has_dispute",
        ),
        migrations.RemoveField(
            model_name="request",
            name="has_milestones",
        ),
        migrations.RemoveField(
            model_name="request",
            name="selected_at",
        ),
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "طلب جديد"),
                    ("offer_selected", "تم اختيار عرض"),
                    ("agreement_pending", "اتفاقية بانتظار الموافقة"),
                    (
                        "awaiting_payment_confirmation",
                        "تم قبول الاتفاقية وبانتظار تأكيد الدفع",
                    ),
                    ("in_progress", "قيد التنفيذ"),
                    ("completed", "مكتمل"),
                    ("disputed", "نزاع"),
                    ("cancelled", "ملغى"),
                    ("rejected", "مرفوض"),
                    ("modified", "معدل بانتظار موافقة العميل"),
                    ("waiting_client_approval", "بانتظار موافقة العميل"),
                    ("selected", "تم اختيار العرض"),
                    ("withdrawn", "منسحب/ملغي من الموظف"),
                ],
                db_index=True,
                default="new",
                max_length=32,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="agreement_due_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="تاريخ ووقت استحقاق الاتفاقية لهذا الطلب.",
                null=True,
                verbose_name="تاريخ استحقاق الاتفاقية",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="assigned_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الموظف المسند",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="العميل",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="details",
            field=models.TextField(
                help_text="وصف مفصل للطلب.", verbose_name="تفاصيل الطلب"
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="estimated_duration_days",
            field=models.PositiveIntegerField(
                help_text="عدد الأيام المتوقع لإنجاز الطلب.",
                verbose_name="المدة التقديرية (أيام)",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="estimated_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="المبلغ المتوقع للطلب.",
                max_digits=12,
                verbose_name="السعر التقديري",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="links",
            field=models.TextField(
                blank=True,
                help_text="روابط أو مراجع إضافية (اختياري).",
                null=True,
                verbose_name="روابط مرتبطة",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="offers_window_ends_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="تاريخ ووقت انتهاء فترة استقبال العروض لهذا الطلب.",
                null=True,
                verbose_name="نهاية فترة استقبال العروض",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "طلب جديد"),
                    ("offer_selected", "تم اختيار عرض"),
                    ("agreement_pending", "اتفاقية بانتظار الموافقة"),
                    (
                        "awaiting_payment_confirmation",
                        "تم قبول الاتفاقية وبانتظار تأكيد الدفع",
                    ),
                    ("in_progress", "قيد التنفيذ"),
                    ("completed", "مكتمل"),
                    ("disputed", "نزاع"),
                    ("cancelled", "ملغى"),
                    ("rejected", "مرفوض"),
                    ("modified", "معدل بانتظار موافقة العميل"),
                    ("waiting_client_approval", "بانتظار موافقة العميل"),
                    ("selected", "تم اختيار العرض"),
                    ("withdrawn", "منسحب/ملغي من الموظف"),
                ],
                db_index=True,
                default="new",
                max_length=32,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="title",
            field=models.CharField(
                help_text="عنوان مختصر للطلب.",
                max_length=255,
                verbose_name="عنوان الطلب",
            ),
        ),
    ]
