# Generated by Django 5.1.2 on 2025-12-28 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0014_remove_request_has_dispute_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="المحتوى")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="comments_files/",
                        verbose_name="ملف مرفق",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الكاتب",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="marketplace.request",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعليق",
                "verbose_name_plural": "تعليقات",
                "ordering": ["created_at"],
            },
        ),
    ]
