# Generated by Django 5.2.7 on 2025-12-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0011_alter_milestone_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="extension_requested_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="عدد أيام التمديد المطلوبة"
            ),
        ),
    ]
