# Generated by Django 5.1.2 on 2025-12-28 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0015_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="request_files/", verbose_name="الملف"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="marketplace.request",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف طلب",
                "verbose_name_plural": "ملفات الطلبات",
            },
        ),
    ]
